package logging

// Application-supplied top-level log record keys.
const (
	ServiceKey            = "service"
	VersionKey            = "version"
	ComponentKey          = "component"
	RequestIDKey          = "request_id"
	SurfaceKey            = "surface"
	InboundKey            = "inbound"
	WSKey                 = "ws"
	UpstreamRequestIDKey  = "upstream_request_id"
	MethodKey             = "method"
	StatusKey             = "status"
	BytesKey              = "bytes"
	DurationKey           = "duration"
	HandshakeDurationKey  = "handshake_duration"
	OutcomeKey            = "outcome"
	FramesKey             = "frames"
	FallbacksKey          = "fallbacks"
	CatalogShapeKey       = "catalog_shape"
	TerminalReasonKey     = "terminal_reason"
	CloseCodeKey          = "close_code"
	MsgsC2UKey            = "msgs_c2u"
	MsgsU2CKey            = "msgs_u2c"
	BytesC2UKey           = "bytes_c2u"
	BytesU2CKey           = "bytes_u2c"
	PanicKey              = "panic"
	TimeoutKey            = "timeout"
	AddrKey               = "addr"
	ErrorKey              = "error"
	StageKey              = "stage"
	CachedValueKey        = "cached_value"
	CachedValueVersionKey = "cached_value_version"
	CachedValueSourceKey  = "cached_value_source"
	TriggerKey            = "trigger"
	FailureClassKey       = "failure_class"
	ExpiresAtKey          = "expires_at"
	RefreshInKey          = "refresh_in"
	AttemptKey            = "attempt"
	AttemptsKey           = "attempts"
	IntervalKey           = "interval"
	VerificationURIKey    = "verification_uri"
	ExpiresInKey          = "expires_in"
	LoginKey              = "login"
	PathKey               = "path"
	ModelKey              = "model"
	MetadataSourceKey     = "metadata_source"
	SkipReasonKey         = "skip_reason"
	ReviewerKey           = "reviewer"
	BuildKey              = "build"
	ConfigKey             = "config"
	EnabledShimsKey       = "enabled_shims"
)
